# Generated by Django 5.2.8 on 2025-11-21 01:36

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityKnowledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("metadata", models.JSONField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category"], name="sales_agent_categor_1018e7_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "prospect_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("tour_scheduled", models.BooleanField(default=False)),
                ("tour_datetime", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="sales_agent_email_2c3651_idx"),
                    models.Index(
                        fields=["tour_scheduled"], name="sales_agent_tour_sc_8f9f0e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("conversation_history", models.JSONField(default=list)),
                ("current_understanding", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="sales_agent.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("event_data", models.JSONField()),
                ("extracted_by_agent", models.CharField(max_length=100)),
                ("source_message", models.TextField()),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_events",
                        to="sales_agent.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="sales_agent_session_2b3b13_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="sales_agent_event_t_1aab11_idx"
                    ),
                ],
            },
        ),
    ]
